# Generated by Django 5.2.8 on 2025-12-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_service_created_at_service_description_service_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='company',
            new_name='user',
        ),
    ]
